
package project;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author 521949
 */
public class page7 extends javax.swing.JFrame {

    data db;
    page1 page1=new page1();

    /**
     * Creates new form page7
     */
    public page7() {
        initComponents();
        db = new data();
        page1.scaleImg(bg_label, "images/c1.jpg");
    }

//    public page7(String q) {
//        initComponents();
//        L.setText(q);
//        db = new data();
//        page1.scaleImg(bg_label, "images/c1.jpg");
//    }

    @Override
    public void dispose() {
        super.dispose();
        db.closeConnection();
    }

    public void message() {
        //String c = L.getText();
        page10 x = new page10();
        int n = JOptionPane.showConfirmDialog(rootPane, "added to cart..select another category?", "add to cart", 1, -1);
        if (n == 0) {
            page2 s = new page2();
            s.setVisible(true);
            dispose();
        }
        if (n == 1) {
            int z = JOptionPane.showConfirmDialog(rootPane, "books added to cart..proceed to checkout?", "conifrmation", 1, -1);
            if (z == 0) {
                x.setVisible(true);
                dispose();
            }
            if (z == 1) {
                page2 y = new page2();
                y.setVisible(true);
                dispose();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbtn = new javax.swing.JButton();
        P1 = new javax.swing.JPanel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        addToCartBtn = new javax.swing.JButton();
        lc = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        bg_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COMICS");
        setPreferredSize(new java.awt.Dimension(1200, 680));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        backbtn.setBackground(new java.awt.Color(52, 211, 254));
        backbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(0, 0, 0));
        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn);
        backbtn.setBounds(70, 590, 170, 40);

        P1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 0), 3, true), "COMICS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(51, 255, 255))); // NOI18N
        P1.setToolTipText("Comics");
        P1.setOpaque(false);

        rb1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rb1.setForeground(new java.awt.Color(51, 255, 0));
        rb1.setText("The Amazing Spider-Man");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        rb2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rb2.setForeground(new java.awt.Color(0, 0, 0));
        rb2.setText("The Jungle Book");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        rb3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rb3.setForeground(new java.awt.Color(102, 255, 0));
        rb3.setText("Tintin: Explorers on the Moon");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });

        rb4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rb4.setForeground(new java.awt.Color(102, 255, 0));
        rb4.setText("Bahubali: Battle of the Bold");
        rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb4ActionPerformed(evt);
            }
        });

        rb5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rb5.setForeground(new java.awt.Color(0, 0, 0));
        rb5.setText("Teenage Mutant Ninja Turtles");
        rb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5ActionPerformed(evt);
            }
        });

        rb6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rb6.setForeground(new java.awt.Color(0, 0, 0));
        rb6.setText("Diary of a Wimpy Kid: Hard Luck");
        rb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P1Layout = new javax.swing.GroupLayout(P1);
        P1.setLayout(P1Layout);
        P1Layout.setHorizontalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb1)
                            .addComponent(rb5)
                            .addComponent(rb3)
                            .addComponent(rb4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb2)
                            .addComponent(rb6))
                        .addGap(0, 53, Short.MAX_VALUE))))
        );
        P1Layout.setVerticalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(rb1)
                .addGap(55, 55, 55)
                .addComponent(rb4)
                .addGap(62, 62, 62)
                .addComponent(rb3)
                .addGap(41, 41, 41)
                .addComponent(rb2)
                .addGap(61, 61, 61)
                .addComponent(rb5)
                .addGap(47, 47, 47)
                .addComponent(rb6)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(P1);
        P1.setBounds(30, 30, 530, 540);

        addToCartBtn.setBackground(new java.awt.Color(51, 242, 255));
        addToCartBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addToCartBtn.setForeground(new java.awt.Color(0, 0, 0));
        addToCartBtn.setText("ADD TO CART");
        addToCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addToCartBtn);
        addToCartBtn.setBounds(330, 590, 197, 40);

        lc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lc.setForeground(new java.awt.Color(0, 255, 255));
        getContentPane().add(lc);
        lc.setBounds(820, 30, 50, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("books in cart:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(690, 30, 130, 40);

        l6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Diary of a Wimpy Kid-Hard Luck-com.jpg"))); // NOI18N
        getContentPane().add(l6);
        l6.setBounds(690, 80, 320, 499);

        l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Teenage Mutant Ninja Turtles-com.jpg"))); // NOI18N
        getContentPane().add(l5);
        l5.setBounds(770, 90, 230, 340);

        l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Bāhubali-Battle of the Bold-com.jpg"))); // NOI18N
        getContentPane().add(l4);
        l4.setBounds(700, 100, 320, 490);

        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Tintin-com.jpg"))); // NOI18N
        getContentPane().add(l3);
        l3.setBounds(660, 80, 350, 490);

        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/The Jungle Book-com.jpg"))); // NOI18N
        getContentPane().add(l2);
        l2.setBounds(670, 80, 320, 500);

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/The Amazing Spider-Man-com.jpg"))); // NOI18N
        getContentPane().add(l1);
        l1.setBounds(650, 80, 360, 430);

        bg_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/c1.jpg"))); // NOI18N
        getContentPane().add(bg_label);
        bg_label.setBounds(0, 0, 1200, 840);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        dispose();
        page2 a = new page2();
        a.setVisible(true);
        
    }//GEN-LAST:event_backbtnActionPerformed

    private void addToCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartBtnActionPerformed
        try {
            String category = P1.getToolTipText();
            
            List<String> bookNames = new ArrayList<>();
            
            if(rb1.isSelected()) bookNames.add(rb1.getText());
            if(rb2.isSelected()) bookNames.add(rb2.getText());
            if(rb3.isSelected()) bookNames.add(rb3.getText());
            if(rb4.isSelected()) bookNames.add(rb4.getText());
            if(rb5.isSelected()) bookNames.add(rb5.getText());
            if(rb6.isSelected()) bookNames.add(rb6.getText());
            
            for(String bookName: bookNames){
                db.insertBook(bookName, category);
            }
            
            int count = db.getTotalBooksCount(category);
            if (count == 0) {
                JOptionPane.showMessageDialog(rootPane, "no book selected");
            } 
            else {
                message();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_addToCartBtnActionPerformed

    private void rb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5ActionPerformed
        l5.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l6.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_rb5ActionPerformed

    private void rb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6ActionPerformed
        l6.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_rb6ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        try {
            int count = db.getTotalBooksCount();
            lc.setText("" + count);
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowActivated

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        l1.setVisible(true);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        l2.setVisible(true);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l1.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
        l3.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_rb3ActionPerformed

    private void rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb4ActionPerformed
        l4.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_rb4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new page7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P1;
    private javax.swing.JButton addToCartBtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel bg_label;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel lc;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    // End of variables declaration//GEN-END:variables
}
