
package project;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 521949
 */
public class page2 extends javax.swing.JFrame {
    
    data db;

    /**
     * Creates new form page2
     */
    public page2() {
        initComponents();
        db = new data();
        new page1().scaleImg(this.bg_label,"images/colour-spectrum.jpg");
    }


    @Override
    public void dispose() {
        super.dispose();
        db.closeConnection();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        exitbtn = new javax.swing.JButton();
        proceedbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        sciencefiction = new javax.swing.JRadioButton();
        romance = new javax.swing.JRadioButton();
        horror = new javax.swing.JRadioButton();
        comic = new javax.swing.JRadioButton();
        mystery = new javax.swing.JRadioButton();
        biography = new javax.swing.JRadioButton();
        cartCountLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bg_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("category\n");
        setBounds(new java.awt.Rectangle(50, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(10000, 1000));
        setPreferredSize(new java.awt.Dimension(1200, 680));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        exitbtn.setBackground(new java.awt.Color(0, 0, 0));
        exitbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 0, 0));
        exitbtn.setMnemonic('P');
        exitbtn.setText("EXIT");
        exitbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255), 3));
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitbtn);
        exitbtn.setBounds(880, 580, 200, 61);

        proceedbtn.setBackground(new java.awt.Color(0, 0, 0));
        proceedbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        proceedbtn.setForeground(new java.awt.Color(255, 0, 0));
        proceedbtn.setMnemonic('p');
        proceedbtn.setText("PROCEED");
        proceedbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 3, true));
        proceedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedbtnActionPerformed(evt);
            }
        });
        getContentPane().add(proceedbtn);
        proceedbtn.setBounds(480, 580, 258, 62);

        backbtn.setBackground(new java.awt.Color(0, 0, 0));
        backbtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 0, 0));
        backbtn.setText("BACK");
        backbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 3, true));
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn);
        backbtn.setBounds(140, 580, 200, 61);

        welcomeLabel.setBackground(new java.awt.Color(255, 51, 51));
        welcomeLabel.setFont(new java.awt.Font("PMingLiU-ExtB", 3, 60)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(51, 255, 255));
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("WELCOME");
        welcomeLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        welcomeLabel.setAutoscrolls(true);
        welcomeLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 3, true));
        getContentPane().add(welcomeLabel);
        welcomeLabel.setBounds(358, 20, 560, 70);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 0), 3, true), "PLEASE SELECT A CATEGORY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI Semibold", 0, 22), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 450));

        buttonGroup1.add(sciencefiction);
        sciencefiction.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        sciencefiction.setForeground(new java.awt.Color(255, 0, 0));
        sciencefiction.setText("Science Fiction");
        sciencefiction.setName("book1"); // NOI18N
        sciencefiction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sciencefictionActionPerformed(evt);
            }
        });

        buttonGroup1.add(romance);
        romance.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        romance.setForeground(new java.awt.Color(255, 0, 0));
        romance.setText("Romance");

        buttonGroup1.add(horror);
        horror.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        horror.setForeground(new java.awt.Color(255, 0, 0));
        horror.setText("Horror");

        buttonGroup1.add(comic);
        comic.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        comic.setForeground(new java.awt.Color(153, 255, 255));
        comic.setText("Comics");
        comic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comicActionPerformed(evt);
            }
        });

        buttonGroup1.add(mystery);
        mystery.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        mystery.setForeground(new java.awt.Color(153, 255, 255));
        mystery.setText("Mystery and Adventure");

        buttonGroup1.add(biography);
        biography.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        biography.setForeground(new java.awt.Color(153, 255, 255));
        biography.setText("Biographies");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sciencefiction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(romance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(horror, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(127, 127, 127)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mystery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(biography, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sciencefiction, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comic, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mystery, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(romance, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horror, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biography, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(170, 110, 840, 450);
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        cartCountLabel.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        cartCountLabel.setForeground(new java.awt.Color(0, 255, 255));
        cartCountLabel.setToolTipText(cartCountLabel.getText());
        cartCountLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        cartCountLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cartCountLabelMouseEntered(evt);
            }
        });
        getContentPane().add(cartCountLabel);
        cartCountLabel.setBounds(1120, 40, 40, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("books in cart:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(960, 40, 160, 30);

        bg_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/colour-spectrum.jpg"))); // NOI18N
        bg_label.setMaximumSize(new java.awt.Dimension(10000, 10000));
        bg_label.setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().add(bg_label);
        bg_label.setBounds(0, 0, 1190, 690);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        
        int choice = JOptionPane.showConfirmDialog(null,
                "Do you want to logout?", "Logout",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE
        );
        
        if(choice == JOptionPane.YES_OPTION){
            dispose();
            page1 s = new page1();
            s.setVisible(true);
                    
        }
        
    }//GEN-LAST:event_backbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    private void proceedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedbtnActionPerformed
        //String b = L.getText();
        int cartCount = Integer.parseInt(cartCountLabel.getText());
        //String a = sciencefiction.getText();
        //System.out.println(b);
        
        if (sciencefiction.isSelected()) {
            dispose();
            page4 z = new page4();
            z.setVisible(true);
            //dispose();
        } 
        else if (romance.isSelected()) {
            dispose();
            page5 y = new page5();
            y.setVisible(true);
            //dispose();

        } 
        else if (horror.isSelected()) {
            dispose();
            page6 x = new page6();
            x.setVisible(true);
            //dispose();
        } 
        else if (comic.isSelected()) {
            dispose();
            page7 w = new page7();
            w.setVisible(true);
            dispose();
        } 
        else if (mystery.isSelected()) {
            dispose();
            page8 r = new page8();
            r.setVisible(true);
            //dispose();
        } 
        else if (biography.isSelected()) {
            dispose();
            page9 t = new page9();
            t.setVisible(true);
            //dispose();
        } 
        else if (cartCount != 0) {
            dispose();
            page10 op = new page10();
            op.setVisible(true);
        } 
        else {
            JOptionPane.showMessageDialog(rootPane, "no category selected.. please select a category");
        }

    }//GEN-LAST:event_proceedbtnActionPerformed

    private void sciencefictionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sciencefictionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sciencefictionActionPerformed

    private void comicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comicActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            int count = db.getTotalBooksCount();
            cartCountLabel.setText("" + count);

        } 
        catch (Exception e) {
            Logger.getLogger(data.LOG_NAME).log(Level.INFO, "Error: {0}", e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_formWindowActivated

    private void cartCountLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartCountLabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cartCountLabelMouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        welcomeLabel.setText("Welcome "+ User.name);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new page2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel bg_label;
    private javax.swing.JRadioButton biography;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cartCountLabel;
    private javax.swing.JRadioButton comic;
    private javax.swing.JButton exitbtn;
    private javax.swing.JRadioButton horror;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mystery;
    private javax.swing.JButton proceedbtn;
    private javax.swing.JRadioButton romance;
    private javax.swing.JRadioButton sciencefiction;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
