/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author Aditya Upadhye
 */
import java.awt.Image;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class page1 extends javax.swing.JFrame {

    Connection con;
    Statement st;
    data db;

    /**
     * Creates new form page1
     */
    public page1() {
        initComponents();
        scaleImg(this.bg_label,"images/book.jpg");
        //System.out.println(bg_label.getIcon());
        
    }

    public void scaleImg(JLabel label,String path) {
        try {
            ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource(path));
            //System.out.println(icon);
            Image img = icon.getImage();
            Image imgscale = img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledicon = new ImageIcon(imgscale);
            label.setIcon(scaledicon);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    @Override
    public void dispose() {
        super.dispose(); 
        db.closeConnection();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pw1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TF1 = new javax.swing.JTextField();
        signUpButton = new javax.swing.JButton();
        signInButton = new javax.swing.JButton();
        bg_label = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("library\n");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new ImageIcon(getClass().getClassLoader().getResource("images/book.jpg")).getImage());
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(1200, 680));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 680));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 680));
        jPanel1.setLayout(null);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Pristina", 3, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("My Library");
        jLabel6.setToolTipText("your library");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(480, 80, 250, 58);

        pw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pw1ActionPerformed(evt);
            }
        });
        pw1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pw1KeyPressed(evt);
            }
        });
        jPanel1.add(pw1);
        pw1.setBounds(190, 340, 280, 30);

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 0));
        jButton3.setText("EXIT");
        jButton3.setToolTipText("exit app");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1240, 630, 240, 60);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("password :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 340, 150, 30);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("username : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 280, 170, 30);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Already have an account? SIGN IN!");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 230, 510, 40);

        TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF1ActionPerformed(evt);
            }
        });
        jPanel1.add(TF1);
        TF1.setBounds(190, 290, 280, 30);

        signUpButton.setBackground(new java.awt.Color(0, 0, 0));
        signUpButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        signUpButton.setForeground(new java.awt.Color(255, 255, 0));
        signUpButton.setText("SIGN UP");
        signUpButton.setToolTipText("create an account");
        signUpButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        jPanel1.add(signUpButton);
        signUpButton.setBounds(230, 460, 180, 50);

        signInButton.setBackground(java.awt.Color.black);
        signInButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        signInButton.setForeground(new java.awt.Color(255, 255, 0));
        signInButton.setText("SIGN IN");
        signInButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        signInButton.setName("signInButton"); // NOI18N
        signInButton.setOpaque(false);
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });
        jPanel1.add(signInButton);
        signInButton.setBounds(30, 460, 160, 50);

        bg_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bg_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/book.jpg"))); // NOI18N
        bg_label.setMaximumSize(new java.awt.Dimension(10000, 10000));
        bg_label.setPreferredSize(new java.awt.Dimension(1200, 680));
        jPanel1.add(bg_label);
        bg_label.setBounds(0, 0, 1200, 680);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 680);
        jPanel1.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("UseSpecificCatch")
    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed

        String username = TF1.getText();
        String password = new String(pw1.getPassword());

        try {
            /*
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "#1506");
            Statement st = con.createStatement();
            String loginQuery = "SELECT * FROM users WHERE username='" + username + "' AND password='" + password + "' ;";
            System.out.println(loginQuery);
            String testQuery = "SELECT * FROM users;";
            
            ResultSet rs = db.newQuery(loginQuery);
            while (rs.next()) {
                System.out.println(rs.getString("username")+" "+rs.getString("name"));
            }
            System.out.println(rs);
            rs.first();
            String db_username = rs.getString("username");
            String db_pswd = rs.getString("password");
            System.out.println(db_username.equals(username) && db_pswd.equals(password));
            */
            
            if(db.login(username, password)){
                dispose();
                page2 page2 = new page2(username);
                page2.setVisible(true);
            } 
            else {
                JOptionPane.showMessageDialog(rootPane, "incorrect username or password");
            }
            
        } 
        catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Unknown error:  "+e.getMessage());
        } 
    }//GEN-LAST:event_signInButtonActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        dispose();
        page3 a = new page3();
        a.setVisible(true);
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pw1ActionPerformed
        String username = TF1.getText();
        String password = new String(pw1.getPassword());

        try {
            /*
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from user_info where username='" + a + "' and password='" + p + "' ;");
            rs.first();
            while(rs.next()){
            for(int k=0; k<5; k++) {
            if(k==0) 
            rs.first();
            else            
            rs.next();
            String x = rs.getString(2);
            String y = rs.getString(3);
            */
            if (db.login(username, password)) {
                dispose();
                page2 n = new page2(username);
                n.setVisible(true);
            } 
            else {
                JOptionPane.showMessageDialog(rootPane, "incorrect username or password");
            }
        } 
        catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Error: "+e.getMessage());
        }
    }//GEN-LAST:event_pw1ActionPerformed

    private void pw1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pw1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pw1KeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            db = new data();
            db.createBooksTable();
            db.createUsersTable();
//            String createQuery = "CREATE TABLE IF NOT EXISTS users(\n"
//                    + "id integer PRIMARY KEY,\n"
//                    + "username text NOT NULL,\n"
//                    + "password varchar(50) NOT NULL,\n"
//                    + "name text);";
//            
//            mydata.createTable(createQuery);
            ResultSet rs = db.connect("SELECT name FROM sqlite_master WHERE type='table';");
            while (rs.next()) {
                System.out.println(rs.getString(1));
            }
            System.out.println("connected to sqlite DB");
            rs.close();
        } 
        catch (Exception e) {
            System.out.println("Error: "+e.getMessage());
        }
    }//GEN-LAST:event_formWindowActivated

    private void TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new page1().setVisible(true);
            }
        });

        System.out.println("hello");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF1;
    private javax.swing.JLabel bg_label;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pw1;
    private javax.swing.JButton signInButton;
    private javax.swing.JButton signUpButton;
    // End of variables declaration//GEN-END:variables
}
