/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author aditya upadhye
 */
import javax.swing.JOptionPane;

public class page3 extends javax.swing.JFrame {
    
    data db;

    /**
     * Creates new form page3
     */
    public page3() {
        initComponents();
        db=new data();
        new page1().scaleImg(this.bg_label,"images/colours-quiz.jpg");
    }

    public page3(String b) {
        initComponents();
        L.setText(b);
        db=new data();
        new page1().scaleImg(this.bg_label,"images/colours-quiz.jpg");
    }

    @Override
    public void dispose() {
        super.dispose();
        db.closeConnection();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        unameTF = new javax.swing.JTextField();
        pswdTF = new javax.swing.JTextField();
        repswdTF = new javax.swing.JTextField();
        createAccount = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        nameTF = new javax.swing.JTextField();
        bg_label = new javax.swing.JLabel();
        L = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIGN UP");
        setBounds(new java.awt.Rectangle(40, 10, 0, 0));
        setPreferredSize(new java.awt.Dimension(1200, 680));
        setResizable(false);
        getContentPane().setLayout(null);

        backBtn.setBackground(new java.awt.Color(0, 255, 255));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 0, 0));
        backBtn.setText("BACK TO HOME");
        backBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(20, 390, 210, 57);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Username :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 76, 137, 35);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Set password :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 122, 180, 43);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Re-check password :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 165, 190, 37);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Full name :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 38, 113, 26);

        unameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameTFActionPerformed(evt);
            }
        });
        getContentPane().add(unameTF);
        unameTF.setBounds(210, 80, 226, 35);

        pswdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswdTFActionPerformed(evt);
            }
        });
        getContentPane().add(pswdTF);
        pswdTF.setBounds(210, 120, 223, 32);
        getContentPane().add(repswdTF);
        repswdTF.setBounds(210, 170, 223, 29);

        createAccount.setBackground(new java.awt.Color(0, 255, 255));
        createAccount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        createAccount.setForeground(new java.awt.Color(0, 0, 0));
        createAccount.setText("CREATE ACCOUNT");
        createAccount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        createAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountActionPerformed(evt);
            }
        });
        getContentPane().add(createAccount);
        createAccount.setBounds(389, 393, 199, 57);

        exitBtn.setBackground(new java.awt.Color(0, 255, 255));
        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(0, 0, 0));
        exitBtn.setText("EXIT");
        exitBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitBtn);
        exitBtn.setBounds(210, 490, 134, 57);

        nameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTFActionPerformed(evt);
            }
        });
        getContentPane().add(nameTF);
        nameTF.setBounds(210, 30, 226, 36);

        bg_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Colours-quiz.jpg"))); // NOI18N
        bg_label.setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().add(bg_label);
        bg_label.setBounds(0, 0, 1200, 680);
        getContentPane().add(L);
        L.setBounds(550, 30, 210, 60);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 20, 460, 190);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        dispose();
        page1 a = new page1();
        a.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void createAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountActionPerformed
        try {

            String z = L.getText();

//            Class.forName("java.sql.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
//            Statement st = con.createStatement();

            String name = nameTF.getText();
            String username = unameTF.getText();
            String pswd = pswdTF.getText();
            String repswd = repswdTF.getText();
            
            String insertQuery="INSERT INTO users(username, password, name)"
                    + " values('" + username + "','" + pswd + "','" + name + "');";

            if (username.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "enter username");
            }
            if (pswd.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "enter password");
            }
            if (repswd.isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "please re-enter passsword ");
            }

            if (pswd.equals(repswd) && !pswd.isEmpty()) {
                db.newUpdateQuery(insertQuery);
                int n = JOptionPane.showConfirmDialog(rootPane, "your account is created.. use app now?", "sign up", 1, -1);
                if (n == 0) {
                    dispose();
                    page2 page2 = new page2(username);
                    page2.setVisible(true);
                }
                if (n == 1) {
                    dispose();
                    page1 a = new page1();
                    a.setVisible(true);
                }                                                                                 
            } 
            else {
                JOptionPane.showMessageDialog(rootPane, "password is not matching");
            }

        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
        }


    }//GEN-LAST:event_createAccountActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        dispose();
        System.exit(0);        
    }//GEN-LAST:event_exitBtnActionPerformed

    private void nameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTFActionPerformed

    private void pswdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswdTFActionPerformed

    private void unameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameTFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new page3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bg_label;
    private javax.swing.JButton createAccount;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField pswdTF;
    private javax.swing.JTextField repswdTF;
    private javax.swing.JTextField unameTF;
    // End of variables declaration//GEN-END:variables
}
