/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 521949
 */
public class page9 extends javax.swing.JFrame {

    data db;
    page1 page1 = new page1();

    /**
     * Creates new form page9
     */
    public page9() {
        initComponents();
        db = new data();
        page1.scaleImg(bg_label, "images/c3.jpg");
    }

    public page9(String p) {
        initComponents();
        L.setText(p);
        db = new data();
        page1.scaleImg(bg_label, "images/c3.jpg");
    }

    @Override
    public void dispose() {
        super.dispose();
        db.closeConnection();
    }
    
    

    public void message() {
        String c = L.getText();
        page10 x = new page10(c);
        int n = JOptionPane.showConfirmDialog(rootPane, "added to cart..select another category?", "add to cart", 1, -1);
        if (n == 0) {
            page2 s = new page2(c);
            s.setVisible(true);
            dispose();
        }
        if (n == 1) {
            int z = JOptionPane.showConfirmDialog(rootPane, "books added to cart..proceed to checkout?", "conifrmation", 1, -1);
            if (z == 0) {
                x.setVisible(true);
                dispose();
            }
            if (z == 1) {
                page2 y = new page2(c);
                y.setVisible(true);
                dispose();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        P1 = new javax.swing.JPanel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        addToCartBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lc = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        bg_label = new javax.swing.JLabel();
        L = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 680));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        backBtn.setBackground(new java.awt.Color(255, 255, 51));
        backBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 0, 0));
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(30, 580, 159, 49);

        P1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 3, true), "BIOGRAPHIES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 28), new java.awt.Color(255, 0, 51))); // NOI18N
        P1.setToolTipText("Biographies");
        P1.setOpaque(false);

        rb1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb1.setForeground(new java.awt.Color(255, 0, 51));
        rb1.setText("Playing It My Way");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        rb2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb2.setForeground(new java.awt.Color(255, 0, 51));
        rb2.setText("Gandhi: My Life is My Message");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        rb3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb3.setForeground(new java.awt.Color(255, 0, 51));
        rb3.setText("Messi: A Biography");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });

        rb4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb4.setForeground(new java.awt.Color(255, 0, 51));
        rb4.setText("Albert Einstein: Out of My Later Years");
        rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb4ActionPerformed(evt);
            }
        });

        rb5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb5.setForeground(new java.awt.Color(255, 0, 51));
        rb5.setText("Dreams from My Father");
        rb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5ActionPerformed(evt);
            }
        });

        rb6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb6.setForeground(new java.awt.Color(255, 0, 51));
        rb6.setText("Mother Teresa: Come Be My Light");
        rb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P1Layout = new javax.swing.GroupLayout(P1);
        P1.setLayout(P1Layout);
        P1Layout.setHorizontalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rb1)
                        .addGap(751, 751, 751))
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb5)
                            .addComponent(rb3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(P1Layout.createSequentialGroup()
                        .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb6)
                            .addComponent(rb2)
                            .addComponent(rb4))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        P1Layout.setVerticalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(rb1)
                .addGap(51, 51, 51)
                .addComponent(rb5)
                .addGap(54, 54, 54)
                .addComponent(rb3)
                .addGap(45, 45, 45)
                .addComponent(rb4)
                .addGap(40, 40, 40)
                .addComponent(rb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(rb6)
                .addGap(43, 43, 43))
        );

        getContentPane().add(P1);
        P1.setBounds(30, 20, 600, 540);

        addToCartBtn.setBackground(new java.awt.Color(255, 255, 51));
        addToCartBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addToCartBtn.setForeground(new java.awt.Color(0, 0, 0));
        addToCartBtn.setText("ADD TO CART");
        addToCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addToCartBtn);
        addToCartBtn.setBounds(230, 580, 221, 49);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("books in cart:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(820, 20, 220, 40);

        lc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lc.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lc);
        lc.setBounds(1030, 20, 50, 40);

        l6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Mother Teresa Come Be My Light-A.jpg"))); // NOI18N
        getContentPane().add(l6);
        l6.setBounds(780, 90, 320, 500);

        l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Dreams from My Father-A.jpg"))); // NOI18N
        getContentPane().add(l5);
        l5.setBounds(780, 90, 320, 500);

        l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Albert Einstein- Out of My Later Years-A.jpg"))); // NOI18N
        getContentPane().add(l4);
        l4.setBounds(780, 90, 320, 500);

        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Messi-A Biography-A.jpg"))); // NOI18N
        getContentPane().add(l3);
        l3.setBounds(780, 90, 320, 500);

        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Gandhi- My Life is My Message-A.jpg"))); // NOI18N
        getContentPane().add(l2);
        l2.setBounds(780, 90, 320, 500);

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Playing It My Way-A.jpg"))); // NOI18N
        getContentPane().add(l1);
        l1.setBounds(780, 90, 325, 500);

        bg_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/c3.jpg"))); // NOI18N
        getContentPane().add(bg_label);
        bg_label.setBounds(0, 0, 1200, 680);
        getContentPane().add(L);
        L.setBounds(570, 580, 260, 70);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        String c = L.getText();
        page2 a = new page2(c);
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void addToCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartBtnActionPerformed
        try {
            String category = P1.getToolTipText();
            
            List<String> bookNames = new ArrayList<>();
            
            if(rb1.isSelected()) bookNames.add(rb1.getText());
            if(rb2.isSelected()) bookNames.add(rb2.getText());
            if(rb3.isSelected()) bookNames.add(rb3.getText());
            if(rb4.isSelected()) bookNames.add(rb4.getText());
            if(rb5.isSelected()) bookNames.add(rb5.getText());
            if(rb6.isSelected()) bookNames.add(rb6.getText());
            
            for(var bookName: bookNames){
                db.insertBook(bookName, category);
            }
            
            /*Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            Statement st = con.createStatement();
            
            HashMap<String,String> map = new HashMap<>();
            String book_name="";
            if (rb1.isSelected()) {
                book_name = rb1.getText();
                //String sql = "insert into books values('" + n1 + "','" + category + "')";
                //st.executeUpdate(sql);
                map.put(book_name, category);
            }
            if (rb2.isSelected()) {
                book_name = rb2.getText();
                //String sql = "insert into books values('" + n2 + "','" + category + "')";
                //st.executeUpdate(sql);
                map.put(book_name, category);

            }
            if (rb3.isSelected()) {
                book_name = rb3.getText();
                //String sql = "insert into books values('" + n3 + "','" + category + "')";
                //st.executeUpdate(sql);
                map.put(book_name, category);

            }
            if (rb4.isSelected()) {
                book_name = rb4.getText();
                //String sql = "insert into books values('" + n4 + "','" + category + "')";
                //st.executeUpdate(sql);
                map.put(book_name, category);

            }
            if (rb5.isSelected()) {
                book_name = rb5.getText();
                //String sql = "insert into books values('" + n5 + "','" + category + "')";
                //st.executeUpdate(sql);
                map.put(book_name, category);

            }
            if (rb6.isSelected()) {
                book_name = rb6.getText();
                //String sql = "insert into books values('" + n6 + "','" + category + "')";
                //st.executeUpdate(sql);
                map.put(book_name, category);

            }
            
            map.forEach((bookName, ctg) -> {
                //String insertQuery = "INSERT INTO books VALUES('"+bookName+"','"+ctg+"');";
                if(! db.insertBook(bookName, ctg)){
                    JOptionPane.showMessageDialog(rootPane, "Error selecting books");
                }
            });

            String sq = "select count(*) from books where category='" + category + "';";
            ResultSet rs = st.executeQuery(sq);
            rs.first();
            int a = rs.getInt(1);
            */
            int count = db.getTotalBooksCount(category);
            if (count == 0) {
                JOptionPane.showMessageDialog(rootPane, "no book selected");
            } 
            else {
                message();
            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Error: " + e.getMessage());
        }
    }//GEN-LAST:event_addToCartBtnActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        l1.setVisible(true);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        l2.setVisible(true);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l1.setVisible(false);     // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
        l3.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_rb3ActionPerformed

    private void rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb4ActionPerformed
        l4.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_rb4ActionPerformed

    private void rb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5ActionPerformed
        l5.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l6.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_rb5ActionPerformed

    private void rb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6ActionPerformed
        l6.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_rb6ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        try {
            /*
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            Statement st = con.createStatement();
            String sql = "select count(*) from books;";
            ResultSet rs = st.executeQuery(sql);
            rs.first();
            int n = rs.getInt(1);
            */
            int count = db.getTotalBooksCount();
            lc.setText("" + count);
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new page9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L;
    private javax.swing.JPanel P1;
    private javax.swing.JButton addToCartBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bg_label;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel lc;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    // End of variables declaration//GEN-END:variables
}
