/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author 521949
 */
public class page8 extends javax.swing.JFrame {

    data db;
    page1 page1 = new page1();

    /**
     * Creates new form page8
     */
    public page8() {
        initComponents();
        db = new data();
        page1.scaleImg(bg_label, "images/c2.jpg");
    }

    public page8(String s) {
        initComponents();
        L.setText(s);
        db = new data();
        page1.scaleImg(bg_label, "images/c2.jpg");
    }

    public void message() {
        String c = L.getText();
        page10 x = new page10(c);
        int n = JOptionPane.showConfirmDialog(rootPane, "added to cart..select another category?", "add to cart", 1, -1);
        if (n == 0) {
            page2 s = new page2(c);
            s.setVisible(true);
            dispose();
        }
        if (n == 1) {
            int z = JOptionPane.showConfirmDialog(rootPane, "books added to cart..proceed to checkout?", "conifrmation", 1, -1);
            if (z == 0) {
                x.setVisible(true);
                dispose();
            }
            if (z == 1) {
                page2 y = new page2(c);
                y.setVisible(true);
                dispose();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbtn = new javax.swing.JButton();
        P1 = new javax.swing.JPanel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        addToCartBtn = new javax.swing.JButton();
        lc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        bg_label = new javax.swing.JLabel();
        L = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MYSTERY AND ADVENTURE");
        setPreferredSize(new java.awt.Dimension(1200, 680));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        backbtn.setBackground(new java.awt.Color(28, 243, 22));
        backbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(0, 0, 0));
        backbtn.setText("back");
        backbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn);
        backbtn.setBounds(40, 560, 161, 53);

        P1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 3, true), "MYSTERY AND ADVENTURE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(51, 255, 0))); // NOI18N
        P1.setToolTipText("Mystery and Adventure");
        P1.setOpaque(false);

        rb1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb1.setForeground(new java.awt.Color(102, 255, 0));
        rb1.setText("The Impossible Rescue");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        rb2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb2.setForeground(new java.awt.Color(102, 255, 0));
        rb2.setText("Touching the Void");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        rb3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb3.setForeground(new java.awt.Color(102, 255, 0));
        rb3.setText("Buried in the Sky");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });

        rb4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb4.setForeground(new java.awt.Color(102, 255, 0));
        rb4.setText("The Final Four");
        rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb4ActionPerformed(evt);
            }
        });

        rb5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb5.setForeground(new java.awt.Color(102, 255, 0));
        rb5.setText("The House on Tradd Street");
        rb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5ActionPerformed(evt);
            }
        });

        rb6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb6.setForeground(new java.awt.Color(102, 255, 0));
        rb6.setText("Payback Time");
        rb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P1Layout = new javax.swing.GroupLayout(P1);
        P1.setLayout(P1Layout);
        P1Layout.setHorizontalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb6)
                    .addComponent(rb5)
                    .addComponent(rb4)
                    .addComponent(rb1)
                    .addComponent(rb2)
                    .addComponent(rb3))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        P1Layout.setVerticalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(rb1)
                .addGap(48, 48, 48)
                .addComponent(rb2)
                .addGap(61, 61, 61)
                .addComponent(rb3)
                .addGap(47, 47, 47)
                .addComponent(rb4)
                .addGap(37, 37, 37)
                .addComponent(rb5)
                .addGap(30, 30, 30)
                .addComponent(rb6)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(P1);
        P1.setBounds(31, 24, 490, 520);

        addToCartBtn.setBackground(new java.awt.Color(54, 245, 35));
        addToCartBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addToCartBtn.setForeground(new java.awt.Color(0, 0, 0));
        addToCartBtn.setText("add to cart");
        addToCartBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        addToCartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addToCartBtn);
        addToCartBtn.setBounds(270, 560, 223, 53);

        lc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lc.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lc);
        lc.setBounds(1050, 20, 50, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("books in cart:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(870, 30, 170, 30);

        l6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Payback Time-mys.jpg"))); // NOI18N
        getContentPane().add(l6);
        l6.setBounds(810, 80, 330, 490);

        l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/The House on Tradd Street-mys.jpg"))); // NOI18N
        l5.setText("jLabel1");
        getContentPane().add(l5);
        l5.setBounds(810, 80, 320, 470);

        l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/The Final Four-mys.jpg"))); // NOI18N
        getContentPane().add(l4);
        l4.setBounds(810, 80, 330, 490);

        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Buried in the Sky-adv.jpg"))); // NOI18N
        getContentPane().add(l3);
        l3.setBounds(810, 80, 334, 490);

        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Touching the Void-adv.jpg"))); // NOI18N
        getContentPane().add(l2);
        l2.setBounds(810, 80, 330, 410);

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/The Impossible Rescue-adv.jpg"))); // NOI18N
        getContentPane().add(l1);
        l1.setBounds(720, 80, 460, 500);

        bg_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/c2.jpg"))); // NOI18N
        bg_label.setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().add(bg_label);
        bg_label.setBounds(0, 0, 1200, 680);
        getContentPane().add(L);
        L.setBounds(620, 520, 210, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        String c = L.getText();
        page2 a = new page2(c);
        a.setVisible(true);
        dispose();// TODO add your handling code here:
    }//GEN-LAST:event_backbtnActionPerformed

    private void addToCartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartBtnActionPerformed
        try {
            String category = P1.getToolTipText();
            
            List<String> bookNames = new ArrayList<>();
            
            if(rb1.isSelected()) bookNames.add(rb1.getText());
            if(rb2.isSelected()) bookNames.add(rb2.getText());
            if(rb3.isSelected()) bookNames.add(rb3.getText());
            if(rb4.isSelected()) bookNames.add(rb4.getText());
            if(rb5.isSelected()) bookNames.add(rb5.getText());
            if(rb6.isSelected()) bookNames.add(rb6.getText());
            
            for(var bookName: bookNames){
                db.insertBook(bookName, category);
            }
            
            /*
            Class.forName("java.sql.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
            Statement st = con.createStatement();
            
            if (rb1.isSelected()) {
                String n1 = rb1.getText();
                String sql = "insert into books values('" + n1 + "','" + category + "')";
                //st.executeUpdate(sql);
                db.newUpdateQuery(sql);

            }
            if (rb2.isSelected()) {
                String n2 = rb2.getText();
                String sql = "insert into books values('" + n2 + "','" + category + "')";
                //st.executeUpdate(sql);
                db.newUpdateQuery(sql);

            }
            if (rb3.isSelected()) {
                String n3 = rb3.getText();
                String sql = "insert into books values('" + n3 + "','" + category + "')";
                //st.executeUpdate(sql);
                db.newUpdateQuery(sql);

            }
            if (rb4.isSelected()) {
                String n4 = rb4.getText();
                String sql = "insert into books values('" + n4 + "','" + category + "')";
                //st.executeUpdate(sql);
                db.newUpdateQuery(sql);

            }
            if (rb5.isSelected()) {
                String n5 = rb5.getText();
                String sql = "insert into books values('" + n5 + "','" + category + "')";
                //st.executeUpdate(sql);
                db.newUpdateQuery(sql);

            }
            if (rb6.isSelected()) {
                String n6 = rb6.getText();
                String sql = "insert into books values('" + n6 + "','" + category + "')";
                //st.executeUpdate(sql);
                db.newUpdateQuery(sql);

            }

            String sq = "select count(*) from books where category='" + m + "';";
            ResultSet rs = st.executeQuery(sq);
            rs.first();
            int a = rs.getInt(1);
            */
            int count = db.getTotalBooksCount(category);
            if (count == 0) {
                JOptionPane.showMessageDialog(rootPane, "no book selected");
            } 
            else {
                message();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Error: "+e.getMessage());
        }        
    }//GEN-LAST:event_addToCartBtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        try {
//            Class.forName("java.sql.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
//            Statement st = con.createStatement();
//            String sql = "select count(*) from books;";
//            ResultSet rs = st.executeQuery(sql);
//            rs.first();
//            int n = rs.getInt(1);
            int totalBooks = db.getTotalBooksCount();
            lc.setText("" + totalBooks);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            
        }
    }//GEN-LAST:event_formWindowActivated

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        l1.setVisible(true);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);   // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        l2.setVisible(true);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l1.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
        l3.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_rb3ActionPerformed

    private void rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb4ActionPerformed
        l4.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_rb4ActionPerformed

    private void rb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5ActionPerformed
        l5.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l6.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_rb5ActionPerformed

    private void rb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6ActionPerformed
        l6.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);    // TODO add your handling code here:
    }//GEN-LAST:event_rb6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new page8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L;
    private javax.swing.JPanel P1;
    private javax.swing.JButton addToCartBtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel bg_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel lc;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    // End of variables declaration//GEN-END:variables
}
