
package project;

/**
 *
 * @author aditya upadhye
 */
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class page4 extends javax.swing.JFrame {
    
    private final data db;

    /**
     * Creates new form page4
     */
    public page4() {
        initComponents();
        db = new data();
        new page1().scaleImg(bg_label, "images/scifi.png");
    }

    public void message() {
        page10 x = new page10();
        int n = JOptionPane.showConfirmDialog(null, "added to cart..select another category?", "add to cart", 1, -1);
        if (n == 0) {
            dispose();
            page2 s = new page2();
            s.setVisible(true);
        }
        if (n == 1) {
            int z = JOptionPane.showConfirmDialog(null, "books added to cart..proceed to checkout?", "conifrmation", 1, -1);
            if (z == 0) {
                dispose();
                x.setVisible(true);
            }
            if (z == 1) {
                dispose();
                page2 y = new page2();
                y.setVisible(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        backbtn = new javax.swing.JButton();
        addtocartBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lc = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        bg_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Science Fiction");
        setPreferredSize(new java.awt.Dimension(1200, 680));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        p1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 3, true), "SCIENCE FICTION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(255, 255, 0))); // NOI18N
        p1.setToolTipText("Science Fiction");
        p1.setOpaque(false);

        rb1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb1.setForeground(new java.awt.Color(255, 255, 0));
        rb1.setText("BORNE");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        rb2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb2.setForeground(new java.awt.Color(255, 255, 0));
        rb2.setText("THE STARS ARE LEGION");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        rb3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb3.setForeground(new java.awt.Color(255, 255, 0));
        rb3.setText("SIX WAKES");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });

        rb4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb4.setForeground(new java.awt.Color(255, 255, 0));
        rb4.setText("WAKING GODS");
        rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb4ActionPerformed(evt);
            }
        });

        rb5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb5.setForeground(new java.awt.Color(255, 255, 0));
        rb5.setText("THE MOON AND THE OTHER");
        rb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5ActionPerformed(evt);
            }
        });

        rb6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb6.setForeground(new java.awt.Color(255, 255, 0));
        rb6.setText("NEW YORK 2140");
        rb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb6)
                    .addComponent(rb5)
                    .addComponent(rb4)
                    .addComponent(rb1)
                    .addComponent(rb2)
                    .addComponent(rb3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(rb1)
                .addGap(43, 43, 43)
                .addComponent(rb2)
                .addGap(43, 43, 43)
                .addComponent(rb3)
                .addGap(39, 39, 39)
                .addComponent(rb4)
                .addGap(33, 33, 33)
                .addComponent(rb5)
                .addGap(37, 37, 37)
                .addComponent(rb6)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(p1);
        p1.setBounds(50, 30, 400, 487);

        backbtn.setBackground(new java.awt.Color(0, 0, 0));
        backbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 0));
        backbtn.setText("BACK");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn);
        backbtn.setBounds(59, 580, 175, 52);

        addtocartBtn.setBackground(new java.awt.Color(0, 0, 0));
        addtocartBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addtocartBtn.setForeground(new java.awt.Color(255, 255, 0));
        addtocartBtn.setText("ADD TO CART");
        addtocartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addtocartBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addtocartBtn);
        addtocartBtn.setBounds(280, 580, 225, 52);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("books in cart:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(1350, 30, 170, 30);

        lc.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        lc.setForeground(new java.awt.Color(255, 255, 0));
        getContentPane().add(lc);
        lc.setBounds(1350, 60, 50, 40);

        l6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/p4/new-york-scifi.png"))); // NOI18N
        l6.setText("jLabel1");
        getContentPane().add(l6);
        l6.setBounds(820, 50, 290, 439);

        l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/p4/the-moon-and-the-other-scifi.png"))); // NOI18N
        getContentPane().add(l5);
        l5.setBounds(770, 50, 390, 500);

        l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/p4/waking-gods-scifi.png"))); // NOI18N
        getContentPane().add(l4);
        l4.setBounds(800, 50, 330, 500);

        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/p4/six-wakes-scifi.png"))); // NOI18N
        l3.setText("jLabel1");
        getContentPane().add(l3);
        l3.setBounds(810, 40, 330, 500);

        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/p4/the-stars-are-legion-scifi.png"))); // NOI18N
        getContentPane().add(l2);
        l2.setBounds(810, 40, 330, 500);

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/p4/borne-scifi.png"))); // NOI18N
        l1.setText("jLabel1");
        getContentPane().add(l1);
        l1.setBounds(820, 40, 332, 498);

        bg_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/p4/scifi.png"))); // NOI18N
        bg_label.setPreferredSize(new java.awt.Dimension(1200, 680));
        getContentPane().add(bg_label);
        bg_label.setBounds(0, 0, 1200, 680);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        dispose();
        page2 page2 = new page2();
        page2.setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void addtocartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addtocartBtnActionPerformed
        try {
            String category = p1.getToolTipText();
            
            List<String> bookNames = new ArrayList<>();
            
            if(rb1.isSelected()) bookNames.add(rb1.getText());
            if(rb2.isSelected()) bookNames.add(rb2.getText());
            if(rb3.isSelected()) bookNames.add(rb3.getText());
            if(rb4.isSelected()) bookNames.add(rb4.getText());
            if(rb5.isSelected()) bookNames.add(rb5.getText());
            if(rb6.isSelected()) bookNames.add(rb6.getText());
            
            for(String bookName: bookNames){
                db.insertBook(bookName, category);
            }
            
            int curCategoryCount = db.getTotalBooksCount(category);
            if (curCategoryCount == 0) {
                JOptionPane.showMessageDialog(rootPane, "no book selected");
            } 
            else {
                message();
            }
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Error: "+e.getMessage());
        }
    }//GEN-LAST:event_addtocartBtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        
        try {
            int count = db.getTotalBooksCount();
            lc.setText("" + count);
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_formWindowActivated

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        l1.setVisible(true);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        l2.setVisible(true);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l1.setVisible(false);
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
        l3.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
    }//GEN-LAST:event_rb3ActionPerformed

    private void rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb4ActionPerformed
        l4.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
    }//GEN-LAST:event_rb4ActionPerformed

    private void rb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5ActionPerformed
        l5.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l6.setVisible(false);
    }//GEN-LAST:event_rb5ActionPerformed

    private void rb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6ActionPerformed
        l6.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
    }//GEN-LAST:event_rb6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new page4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addtocartBtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel bg_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel lc;
    private javax.swing.JPanel p1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    // End of variables declaration//GEN-END:variables
}
