/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author aditya upadhye
 */
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class page6 extends javax.swing.JFrame {

    data db;
    page1 page1 = new page1();

    /**
     * Creates new form page6
     */
    public page6() {
        initComponents();
        db = new data();
        page1.scaleImg(bg_label, "images/hr.jpg");
    }

    public page6(String x) {
        initComponents();
        L.setText(x);
        db = new data();
        page1.scaleImg(bg_label, "images/hr.jpg");
    }

    public void message() {
        String c = L.getText();
        page10 x = new page10(c);
        int n = JOptionPane.showConfirmDialog(rootPane, "added to cart..select another category?", "add to cart", 1, -1);
        if (n == 0) {
            page2 s = new page2(c);
            s.setVisible(true);
            dispose();
        }
        if (n == 1) {
            int z = JOptionPane.showConfirmDialog(rootPane, "books added to cart..proceed to checkout?", "conifrmation", 1, -1);
            if (z == 0) {
                x.setVisible(true);
                dispose();
            }
            if (z == 1) {
                page2 y = new page2(c);
                y.setVisible(true);
                dispose();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        P1 = new javax.swing.JPanel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb5 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        addToCardBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lc = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        bg_label = new javax.swing.JLabel();
        L = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HORROR");
        setPreferredSize(new java.awt.Dimension(1200, 680));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        backBtn.setBackground(new java.awt.Color(255, 255, 0));
        backBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backBtn.setText("BACK");
        backBtn.setMaximumSize(new java.awt.Dimension(90, 50));
        backBtn.setPreferredSize(new java.awt.Dimension(89, 35));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(60, 570, 187, 47);

        P1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 51), 3, true), "HORROR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24), new java.awt.Color(255, 0, 0))); // NOI18N
        P1.setToolTipText("Horror");
        P1.setOpaque(false);

        rb1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb1.setForeground(new java.awt.Color(255, 0, 51));
        rb1.setText("The Man of Legends");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        rb2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb2.setForeground(new java.awt.Color(255, 0, 51));
        rb2.setText("The Stopped Heart:A Novel");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        rb3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb3.setForeground(new java.awt.Color(255, 0, 51));
        rb3.setText("The Walking Dead");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });

        rb4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb4.setForeground(new java.awt.Color(255, 0, 51));
        rb4.setText("Awakened: A Novel");
        rb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb4ActionPerformed(evt);
            }
        });

        rb5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb5.setForeground(new java.awt.Color(255, 0, 51));
        rb5.setText("100 Days of Death");
        rb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb5ActionPerformed(evt);
            }
        });

        rb6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rb6.setForeground(new java.awt.Color(255, 0, 51));
        rb6.setText("The Map of Moments");
        rb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P1Layout = new javax.swing.GroupLayout(P1);
        P1.setLayout(P1Layout);
        P1Layout.setHorizontalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb1)
                    .addComponent(rb3)
                    .addComponent(rb2))
                .addGap(93, 93, 93)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb5)
                    .addComponent(rb6)
                    .addComponent(rb4))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        P1Layout.setVerticalGroup(
            P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1)
                    .addComponent(rb4))
                .addGap(99, 99, 99)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb2)
                    .addComponent(rb5))
                .addGap(105, 105, 105)
                .addGroup(P1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb3)
                    .addComponent(rb6))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        getContentPane().add(P1);
        P1.setBounds(40, 20, 790, 420);

        addToCardBtn.setBackground(new java.awt.Color(255, 255, 0));
        addToCardBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addToCardBtn.setText("ADD TO CART");
        addToCardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCardBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addToCardBtn);
        addToCardBtn.setBounds(320, 570, 205, 47);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("books in cart:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(950, 30, 170, 40);

        lc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lc.setForeground(new java.awt.Color(255, 0, 51));
        getContentPane().add(lc);
        lc.setBounds(1120, 30, 50, 40);

        l5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/100 Days of Death-hor.jpg"))); // NOI18N
        getContentPane().add(l5);
        l5.setBounds(860, 80, 270, 360);

        l6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/The Map of Moments-hor.jpg"))); // NOI18N
        getContentPane().add(l6);
        l6.setBounds(850, 70, 330, 500);

        l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Awakened- A Novel-hor.jpg"))); // NOI18N
        getContentPane().add(l4);
        l4.setBounds(850, 80, 320, 490);

        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/The Walking Dead-hor.jpg"))); // NOI18N
        getContentPane().add(l3);
        l3.setBounds(850, 90, 320, 500);

        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/The Man of Legends-hor.jpg"))); // NOI18N
        getContentPane().add(l1);
        l1.setBounds(890, 140, 230, 350);

        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/The Stopped Heart-A Novel-hor.jpg"))); // NOI18N
        getContentPane().add(l2);
        l2.setBounds(840, 80, 330, 470);

        bg_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/hr.jpg"))); // NOI18N
        getContentPane().add(bg_label);
        bg_label.setBounds(0, 0, 1400, 780);
        getContentPane().add(L);
        L.setBounds(640, 520, 180, 60);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        String c = L.getText();
        page2 a = new page2(c);
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void addToCardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCardBtnActionPerformed
        try {
            String category = P1.getToolTipText();
            
            List<String> bookNames = new ArrayList<>();
            
            if(rb1.isSelected()) bookNames.add(rb1.getText());
            if(rb2.isSelected()) bookNames.add(rb2.getText());
            if(rb3.isSelected()) bookNames.add(rb3.getText());
            if(rb4.isSelected()) bookNames.add(rb4.getText());
            if(rb5.isSelected()) bookNames.add(rb5.getText());
            if(rb6.isSelected()) bookNames.add(rb6.getText());
            
            for(var bookName: bookNames){
                db.insertBook(bookName, category);
            }
            
            
//            Class.forName("java.sql.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
//            Statement st = con.createStatement();
//            if (rb1.isSelected()) {
//                String n1 = rb1.getText();
//                String sql = "insert into books values('" + n1 + "','" + category + "');";
//                //st.executeUpdate(sql);
//                db.newUpdateQuery(sql);
//
//            }
//            if (rb2.isSelected()) {
//                String n2 = rb2.getText();
//                String sql = "insert into books values('" + n2 + "','" + category + "');";
//                //st.executeUpdate(sql);
//                db.newUpdateQuery(sql);
//
//            }
//            if (rb3.isSelected()) {
//                String n3 = rb3.getText();
//                String sql = "insert into books values('" + n3 + "','" + category + "');";
//                //st.executeUpdate(sql);
//                db.newUpdateQuery(sql);
//
//            }
//            if (rb4.isSelected()) {
//                String n4 = rb4.getText();
//                String sql = "insert into books values('" + n4 + "','" + category + "');";
//                //st.executeUpdate(sql);
//                db.newUpdateQuery(sql);
//
//            }
//            if (rb5.isSelected()) {
//                String n5 = rb5.getText();
//                String sql = "insert into books values('" + n5 + "','" + category + "');";
//                //st.executeUpdate(sql);
//                db.newUpdateQuery(sql);
//
//            }
//            if (rb6.isSelected()) {
//                String n6 = rb6.getText();
//                String sql = "insert into books values('" + n6 + "','" + category + "');";
//                //st.executeUpdate(sql);
//                db.newUpdateQuery(sql);
//
//            }
//            String sq = "select count(*) from books where category='" + category + "';";
//            ResultSet rs = st.executeQuery(sq);
//            rs.first();
//            int a = rs.getInt(1);

            int count = db.getTotalBooksCount(category);
            if (count == 0) {
                JOptionPane.showMessageDialog(rootPane, "no book selected");
            } 
            else {
                message();
            }

            
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error: "+e.getMessage());
            //System.exit(0);
        }
    }//GEN-LAST:event_addToCardBtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        try {
//            Class.forName("java.sql.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/project", "root", "");
//            Statement st = con.createStatement();
//            String sql = "select count(*) from books;";
//            ResultSet rs = st.executeQuery(sql);
//            rs.first();
//            int n = rs.getInt(1);
            int allbookCount = db.getTotalBooksCount();
            lc.setText("" + allbookCount);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error: "+e.getMessage());
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowActivated

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        l1.setVisible(true);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        l2.setVisible(true);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);
        l1.setVisible(false);
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
        l3.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);         
    }//GEN-LAST:event_rb3ActionPerformed

    private void rb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb4ActionPerformed
        l4.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l5.setVisible(false);
        l6.setVisible(false);       
    }//GEN-LAST:event_rb4ActionPerformed

    private void rb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb5ActionPerformed
        l5.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l6.setVisible(false);        
    }//GEN-LAST:event_rb5ActionPerformed

    private void rb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb6ActionPerformed
        l6.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);        
    }//GEN-LAST:event_rb6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(page6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(page6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(page6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(page6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new page6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L;
    private javax.swing.JPanel P1;
    private javax.swing.JButton addToCardBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel bg_label;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel lc;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    // End of variables declaration//GEN-END:variables
}
